package com.rs.cdpapp.mapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.RowMapper;

import com.rs.cdpapp.dto.CimsUpdatedDto;

public class CimsUpdatedMapper implements RowMapper<CimsUpdatedDto> {

	private Logger logger = LoggerFactory.getLogger(getClass());
	
	@Override
	public CimsUpdatedDto  mapRow(ResultSet rs, int rowNum)  {
		
		CimsUpdatedDto dto=new CimsUpdatedDto();
		try{
		
			dto.setLocation(rs.getString("SLOCATION"));
		//dto.setFinalStatus(rs.getString("sAckFinalStatus"));
//		dto.setEmployeeCode(rs.getString("sEMPCODE"));
			dto.setOperator(rs.getString("SOPERATOR"));
		dto.setComplaintOrigination(rs.getString("sComplaintOrigination"));
		dto.setComplaintReopenOrigination(rs.getString("stxReopenOrigination"));
		dto.setAddressTo(rs.getString("sctxtenamAddressedTo"));
		dto.setIsClosureAccepted(rs.getString("sIRDAAccepted"));
		dto.setIsClosureAccesspted(rs.getString("sIRDAAcceptedDisp"));
		dto.setClosureRequstLetterDate(rs.getString("sIRDALetterDate"));
		dto.setClosureRequestLetterDate(rs.getString("sIRDALetterDateDisp"));
		dto.setIsClosureViolated(rs.getString("sIRDAVRemarks"));
		dto.setClosureViolationRemark(rs.getString("sIRDAVRemarksDisp"));
		dto.setIsRegularityImprovementSuggested(rs.getString("sIRDASuggestion"));
		dto.setClosureActionSuggested(rs.getString("sIRDAActionDisp"));
		dto.setCloseactionSuggested(rs.getString("sIRDAAction"));
		dto.setRegularityImprovementSuggestions(rs.getString("sIRDASuggestionDisp"));
		dto.setPriorityHandlingId(rs.getString("sPriorityHandlingID"));
		dto.setPriorityHandlingName(rs.getString("sPriorityHandlingName"));
		dto.setRemarks(rs.getString("sRemarks"));
		dto.setCoverNoteNumber(rs.getString("sCovernoteSRCHSpy"));
		dto.setCampaignCode(rs.getString("sCampCodeSRCHSpy"));
		dto.setPolicyAddress(rs.getString("sCitySRCH_1"));
		dto.setChequeNumber(rs.getString("schqnosrch"));
		dto.setChequeNo(rs.getString("scheque_number"));
		dto.setVehicleNumber(rs.getString("svehiclenosrch_1"));
//		dto.setTelephoneNumber(rs.getString("sTelnoSpy"));
		dto.setAddress(rs.getString("sAddressDisp1"));
		dto.setPermanentAddress(rs.getString("sPermAddressDisp1"));
		dto.setPermanentMobile(rs.getString("spermaddressdisp4"));
		dto.setDeliveryDate(rs.getString("sDeliveryDtDisp"));
		dto.setMailingDate(rs.getString("sMailingDtDisp"));
		dto.setDespatchDate(rs.getString("sdespdtdisp"));
		dto.setDeliveryStatus(rs.getString("sDeliveryStatusDisp"));
//		dto.setConverNoteIssueDate(rs.getString("sCoveNoteIssueDateDisp"));
		dto.setConsignmentNumber(rs.getString("sConsignNoDisp"));
		dto.setModeOfDispatch(rs.getString("sDespModeDisp"));
		dto.setDespatchThrough(rs.getString("sDespThruDisp"));
		dto.setDeliveredTo(rs.getString("sDeliveredToDisp"));
		dto.setSearchCriteria(rs.getString("sSearchCriteria"));
//		dto.setName(rs.getString("sNameSRCH"));
		dto.setNameSearchBy(rs.getString("sNamesearchBy"));
		dto.setChequeNumberPay(rs.getString("sChqnoSRCH"));
		dto.setPolicies(rs.getString("sPolicy"));
		dto.setPhoneNo(rs.getString("sContactNo"));
		dto.setVip(rs.getString("sVIP"));
		dto.setPolicyAsh(rs.getString("sPolicynoSRCH"));
//		dto.setProductName(rs.getString("sProductName"));
//		dto.setCampaignCode(rs.getString("sCampCodeSRCH"));
		dto.setCombiPolicy(rs.getString("sCombiPolicynoSRCH"));
		dto.setLifePolicy(rs.getString("sLifepolicynoSRCH"));
//		dto.setPolicyAddress(rs.getString("sCitySRCH"));
//		dto.setBankAccountNumber(rs.getString("sBankACSRCH"));
		dto.setDebitCard(rs.getString("schqnosrch_1"));
		dto.setCreditCard(rs.getString("svehiclenosrch_1"));
		dto.setEmail(rs.getString("sEmailSRCH"));
//		dto.setHealthCardNumber(rs.getString("sHCnoSRCH"));
		dto.setTeleNumber(rs.getString("sTelno"));
		dto.setEnterAgentCode(rs.getString("sAgCode1"));
//		dto.setTopRight(rs.getString("sAgentdocunid"));
     	dto.setAgCode(rs.getString("sagent"));
     	dto.setEnterAgentCode(rs.getString("sagcode1"));
//		dto.setAgnetName(rs.getString("sAgName"));
//		dto.setDateOfBirth(rs.getString("sAgDOB"));
//		dto.setAgMobileNumber(rs.getString("sAgMobileno"));
		dto.setAgCity(rs.getString("sAgLocation"));
		dto.setAgState(rs.getString("sAgState"));
		dto.setRegion(rs.getString("sAgRegion"));
		dto.setEmaiId(rs.getString("sAgEmailid"));
		dto.setLicencedNonLicenced(rs.getString("sAgLicence"));
		dto.setPanNo(rs.getString("sAgPanno"));
		dto.setLifePolicyAsh(rs.getString("sLifePolicynodisp"));
		dto.setCombiPolicyAsh(rs.getString("sCombiPolicynodisp"));
		dto.setPolicyPeriodFromTp(rs.getString("sPeriodFromdispTP"));
		dto.setPolicyPeriodToTp(rs.getString("sPeriodTodispTP"));
		dto.setVehicalAsh(rs.getString("sVehiclenodisp"));
		dto.setVehicalMake(rs.getString("sVehiclemakedisp"));
		dto.setModel(rs.getString("SMODELDISP"));
//		dto.setPolicyPassword(rs.getString("sPolicyPassworddisp"));
		dto.setRegisteredNumber(rs.getString("SREGPHDISP"));
//		dto.setMobileNumber(rs.getString("seditMobPh_2"));
		dto.setState(rs.getString("SState"));
		dto.setMobileNumber(rs.getString("smobile"));
		dto.setAlernateMobileNumber(rs.getString("smobile2"));
		dto.setTelephoneNumber(rs.getString("stelno"));
		dto.setProductName(rs.getString("sproductdesc"));
//		dto.setCampaignCode(rs.getString("etxtcampcodesrchspy"));
		dto.setPolicyPeriodFrom(rs.getString("dtpolicyincepdate"));
		dto.setPolicyPeriodTo(rs.getString("dtpolicyexpdate"));
		dto.setEnterAgentCode(rs.getString("sagcode1"));
	    dto.setAgnetName(rs.getString("sagent_name"));
	    dto.setAgentMobileNo(rs.getString("sagmobileno"));
	    dto.setBankAccountNumber(rs.getString("sbank_ac_number"));
	    dto.setChequeNumber(rs.getString("scheque_number"));
       dto.setReceiptNumber(rs.getString("sreceiptno"));
        dto.setClientPremium(rs.getNString("sclient_premium"));
        dto.setProcessingUnit(rs.getString("spudisp"));
        dto.setStatus(rs.getString("swwcstatusdisp"));
        dto.setFinalStatus(rs.getString("scurrentstatus"));
//		dto.setAlernateMobileNumber(rs.getString("SAltMob_3"));
       dto.setEmail4(rs.getString("sEmail_4"));
		dto.setResidencePhone(rs.getString("sResPh_5"));
		dto.setOfficePhone(rs.getString("sOfficePh_6"));
		dto.setOfficeFax(rs.getString("sOfficeFax_7"));
//		dto.setReceiptNumber(rs.getString("sReceiptNodisp"));
//		dto.setProcessingUnit(rs.getString("sPUdisp"));
//		dto.setAgentMobileNo(rs.getString("sAgentmobilNo"));
		dto.setRenewalIdvNumber(rs.getString("sWWCIDVdisp"));
		dto.setRenewalNcb(rs.getString("sWWCRnlNCBdisp"));
		dto.setRenewalPremium(rs.getString("sWWCPremiumdisp"));
		dto.setOnlineRenewalOption(rs.getString("sWWCOnlineRenewalOptiondisp"));
		dto.setSatisfactoryScore(rs.getString("sSatisfy_Score_TX"));
		dto.setCustomerPolicyAsh(rs.getString("sCustPolicynodisp"));
		dto.setHealthCardNo(rs.getString("sHCnodisp"));
		dto.setClaimReportedNew(rs.getString("sClaimReportNewDisp"));
		dto.setClaimPaid(rs.getString("sClaimPaidDisp"));
		dto.setLinkNumber(rs.getString("sLinkDisp"));
		dto.setResponseCommitedMonth(rs.getString("sResponseMon1"));
		dto.setResponseCommitedYear(rs.getString("sResponseyear1"));
    	dto.setClaims(rs.getString("sclaimpaiddisp"));
		dto.setCovid19(rs.getString("scovidDisp"));
		dto.setMailSentForComplaintClaim(rs.getString("sComplaintClaimMailSent"));
		dto.setIntimationOfBccMembers(rs.getString("sBCCMembers"));
		dto.setCity(rs.getString("sClaimscity"));
		dto.setClaimLocation(rs.getString("sClaimLocation"));
		dto.setClaimArea(rs.getString("sClaimArea"));
		dto.setNewArea(rs.getString("sClaimAreaOther"));
     	dto.setInteractionType(rs.getString("sInteractionTypeDisp"));
     	dto.setClaimHour(rs.getString("SClaimHours"));
     	dto.setClaimMin(rs.getString("SClaimMins"));
     	dto.setClaimAM(rs.getString("SClaimAM"));
     	dto.setSubUnderLyingCause3(rs.getString("scbunderlyingcause_7"));
     	dto.setAddress3(rs.getString("sctxtadd3"));
     	dto.setAddress4(rs.getString("sctxtadd4"));
		dto.setClassification(rs.getString("sIClassificationDisp"));
		dto.setHealthSubCategory(rs.getString("sHealthSubCat"));
		dto.setUnderlyingCause(rs.getString("sCS_OPS"));
		dto.setStateIc(rs.getString("sCtxtAState"));
		dto.setCityIc(rs.getString("sCtxtAcity"));
		dto.setIrdaStateId(rs.getString("sstateHIDE"));
		dto.setReceivedRenewalNotice(rs.getString("sRenewalNotice"));
		dto.setReceivedRenewalTeamCallback(rs.getString("sRenewalTeamCallback"));
		dto.setInstaPayLink(rs.getString("sInstapaylink"));
		dto.setCustomerEmail(rs.getString("sCustemail"));
		dto.setMailRequestSent(rs.getString("sMailrequest"));
		dto.setD2c(rs.getString("sd2c"));
		dto.setSelectNeft(rs.getString("sNEFTClaim_1"));
		dto.setNeftTransferForm(rs.getString("sNEFTClaimsForm_1"));
		dto.setCustomerMailId1(rs.getString("sCustEmaildisp_1"));
		dto.setSelectChangeRequestFormForInclusion(rs.getString("sClaim_2"));
		dto.setChangeReqyestFormForInclusionForInsuredProcedure(rs.getString("sClaimsForm_2"));
		dto.setCustomerEmailId2(rs.getString("sCustEmaildisp_2"));
		dto.setSelectChangeRequestForm(rs.getString("sClaim_3"));
		dto.setChangeRequestFormForSumIlnsuredProcedure(rs.getString("sClaimsForm_3"));
		dto.setCustomerMailId3(rs.getString("sCustEmaildisp_3"));
		dto.setSelectNameTransferMotorCarFormForInclusion(rs.getString("sClaim_4"));
		dto.setNameTransferFormMotorCar(rs.getString("sClaimsForm_4"));
		dto.setCustomerMailId4(rs.getString("sCustEmaildisp_4"));
		dto.setSelectNameTransferTwoWheelerFormForInclusion(rs.getString("sClaim_5"));
		dto.setNameTransferFormForTwoWheeler(rs.getString("sClaimsForm_5"));
		dto.setCustomerMailId5(rs.getString("sCustEmaildisp_5"));
		dto.setSelectProposerNameChangeRequestForm(rs.getString("sClaim_6"));
		dto.setProposerNameChangeForm(rs.getString("sClaimsForm_6"));
		dto.setCustomerMailId(rs.getString("sCustEmaildisp_6"));
		dto.setRetentionTool(rs.getString("sRetention_Tool"));
		dto.setBranch(rs.getString("sBranch"));
		dto.setPremium(rs.getString("sPremiumAmountDisp"));
		dto.setAcknowledgedmentSent(rs.getString("sAckStatusDisp"));
		dto.setFinalResolutionSent(rs.getString("sFinalResStatusDisp"));
		dto.setClaimForms(rs.getString("sClaimsForm"));
		dto.setCustomerEmailDisp(rs.getString("sCustEmaildisp"));
		dto.setIrdaOriginalTokenNumber(rs.getString("sOIRDATokenNo"));
		dto.setComplaintInformed(rs.getString("sComplaintInformedDisp"));
		dto.setAcceptedRejected(rs.getString("sAccepRej_1"));
		dto.setDoYouWantToToReassign(rs.getString("sReassign"));
		dto.setReassignto(rs.getString("sReassignTo"));
		dto.setIntimatedBy(rs.getString("sIntimatedBy"));
		dto.setIntimatedDateAndTime(rs.getString("sIntDateTime"));
		dto.setDateOfLoss(rs.getString("sDateofloss"));
		dto.setTimeOfLossHours(rs.getString("sClaimHours"));
		dto.setTimeOfLossMin(rs.getString("sClaimMins"));
		dto.setTimeOfLossAm(rs.getString("sClaimAM"));
		dto.setRepairerName(rs.getString("SRepairerName"));
		dto.setRepairerAddress(rs.getString("SRepairerAddss"));
		dto.setRepairerContact(rs.getString("SRepairerContNo"));
		dto.setRelationshipOfTheCaller(rs.getString("SRelationship"));
		dto.setSpocPersonToBeContacted(rs.getString("SPersonSpoc"));
		dto.setSpocPersonMobileNumber(rs.getString("SMobilenoClaim"));
		dto.setDriverNameAtTheTimeOfAccident(rs.getString("SDriverName"));
		dto.setIsInjured(rs.getString("SIsInjured"));
		dto.setAccidentState(rs.getString("SAccState"));
		dto.setAccidentCity(rs.getString("SAccCity"));
		dto.setCurrentVehicalLocation(rs.getString("SCurrentVLocation"));
		dto.setLossLocation(rs.getString("SLossLocation"));
     	dto.setNatureOfLoss(rs.getString("sNatureofloss"));
		dto.setModeOfIntimation(rs.getString("sModofIntimation"));
		dto.setDoYouWantToDpReassign(rs.getString("sDPReassign"));
		dto.setDpReassignTo(rs.getString("sDPReassignTo"));
		dto.setIrdaComments(rs.getString("sIRDAComment"));
		dto.setApproverComments(rs.getString("sApprComment"));
		dto.setCommentsComplaintMotorClaim(rs.getString("sCustomerUpdation"));
		dto.setNatureOfRootCause(rs.getString("sNRCause"));
		dto.setResolutionForRootCause(rs.getString("sCAComment"));
		dto.setRootCauseFixed(rs.getString("sRCF"));
		dto.setCommunicateWithTheCustomer(rs.getString("sCommunicate"));
		dto.setSelectTheModeOfCommunication(rs.getString("sModeCom"));
		dto.setMailWillBeSentTo(rs.getString("sCCMail"));
		dto.setDoYouWantToCloseTheCall(rs.getString("sCloseCall"));
//		dto.setFeedback(rs.getString("schkfeedback"));
		dto.setFollowUpCount(rs.getString("SFollowUpCount"));
		dto.setFollowUpDays(rs.getString("snmFollowUpDays"));
		dto.setFollowupDone(rs.getString("sFollowUpDone"));
		dto.setFollowUpDate(rs.getString("sFollowUpDate"));
//		dto.setResolutionMode1(rs.getString("sResolutionMode1"));
//		dto.setResolutionMode2(rs.getString("sResolutionMode2"));
//		dto.setResolutionMode3(rs.getString("sResolutionMode3"));
//		dto.setResolutionMode4(rs.getString("sResolutionMode4"));
		dto.setActivityNo(rs.getString("sActivityno"));
		dto.setActivityName(rs.getString("sActivityname"));
		dto.setFlag(rs.getString("sFlag"));
		dto.setFunction(rs.getString("sFunction"));
		dto.setThirdParty(rs.getString("sThirdParty"));
		dto.setSlaDate(rs.getString("sDatetimeLog_1"));
		dto.setTeamName(rs.getString("sTeamName"));
		//dto.setMembersResponsible(rs.getString("sMemberResp"));
		dto.setSla(rs.getString("sSLA"));
		dto.setEndDateTime(rs.getString("sSLA1DateTime"));
		dto.setEscalationTo(rs.getString("sEscalation1"));
//		dto.setAshNumber(rs.getString("ctxtActivityno_1"));
//		dto.setActivityName1(rs.getString("ctxtActivityname_1"));
		dto.setConditions(rs.getString("sCondition"));
		dto.setSla1(rs.getString("sSLA_1"));
	dto.setEndDateTime2(rs.getString("sSLA2DateTime"));
		dto.setEscalationTo2(rs.getString("sEscalation2"));
		dto.setEscalationTo3(rs.getString("sescalation3"));
		dto.setSla2(rs.getString("sSLA_2"));
	dto.setEndDateTime3(rs.getString("sSLA3DateTime"));
		dto.setIrdaComplaintTypeId(rs.getString("sIRDAID"));
		dto.setIrdaComplaintDescriptionId(rs.getString("sIRDADescID"));
		dto.setIrdaTat(rs.getString("sIRDATAT"));
//		dto.setActivitynoLog(rs.getString("sActivitynoLog"));
		dto.setActivityNameLog(rs.getString("sActivitynameLog"));
//		dto.setIfReassignedToWhom(rs.getString("sReassignedLog"));
//		dto.setWaitingDays(rs.getString("sWaitingtimeLog"));
		dto.setAwbNumber(rs.getString("sAWBNumber"));
		dto.setSerialNumber(rs.getString("SERIALNO"));
//		dto.setDespatchDate(rs.getString("DTCAPTUREDATE"));
		dto.setIsClosureRequsted(rs.getString("sIRDALetterDate"));
        dto.setAddress1(rs.getString("sCtxtAdd1"));
        dto.setAddress2(rs.getString("sCtxtAdd2"));
        dto.setAddress(rs.getString("sCtxtAdd3"));
        dto.setAddress(rs.getString("sCtxtAdd4"));
        dto.setIsAddressCorrection(rs.getString("sAdressCorrection"));
        dto.setIsAddressCorrectionDis(rs.getString("sAdressCorrectiondisp"));
        dto.setPincode(rs.getString("sAPincode"));
		dto.setCityCode(rs.getString("sACCityCodeDB"));
		dto.setStateId(rs.getString("sACStateID"));
		dto.setCityId(rs.getString("sACCityID"));
		dto.setStateCode(rs.getString("sACStateCodeDB"));
		dto.setIrdaCityId(rs.getString("SCityHIDE"));
		dto.setSubUnderLyingCause1(rs.getString("scbUnderlyingCause_5"));
		dto.setSubUnderLyingCause2(rs.getString("scbUnderlyingCause_6"));
		dto.setSubUnderLyingCause1(rs.getString("scbUnderlyingCause_7"));
		dto.setFeedback(rs.getString("sfeedback"));
		dto.setActivityNumber(rs.getString("SACTIVITYNO"));
		
	    dto.setActivitynoLog(rs.getString("SActivitynoLog"));
		dto.setIfReassignedToWhom(rs.getString("sreassignedlog"));
		dto.setWaitingDays(rs.getString("swaitingtimelog"));
		
		
		
		
		
		 
		  dto.setiType(rs.getString("STYPEOFINTERACTION"));
		  dto.setiCode(rs.getString("SINTERACTIONCLASSIFICATION"));
		  dto.setUcCode(rs.getString("SINTERACTIONCAUSE"));
		  dto.setCustomerName(rs.getString("SCUSTOMERNAME"));
//		dto.setFinalStatus(rs.getString("sAckFinalStatus"));
		dto.setEmployeeCode(rs.getString("sempcode"));
		dto.setComplaintOrigination(rs.getString("sComplaintOrigination"));
		dto.setComplaintReopenOrigination(rs.getString("stxReopenOrigination"));
		dto.setAddressTo(rs.getString("sctxtenamAddressedTo"));
		dto.setIsClosureAccepted(rs.getString("sIRDAAccepted"));
		dto.setIsClosureAccesspted(rs.getString("sIRDAAcceptedDisp"));
//		dto.setClosureRequstLetterDate(rs.getString("sIRDALetterDate"));
		dto.setClosureRequestLetterDate(rs.getString("sIRDALetterDateDisp"));
		dto.setIsClosureViolated(rs.getString("sIRDAVRemarks"));
		dto.setClosureViolationRemark(rs.getString("sIRDAVRemarksDisp"));
		dto.setIsRegularityImprovementSuggested(rs.getString("sIRDASuggestion"));
//		dto.setClosureActionSuggested(rs.getString("sIRDAActionDisp"));
//		dto.setCloseactionSuggested(rs.getString("sIRDAAction"));
		dto.setRegularityImprovementSuggestions(rs.getString("sIRDASuggestionDisp"));
//		dto.setPriorityHandlingId(rs.getString("sPriorityHandlingID"));
//		dto.setPriorityHandlingName(rs.getString("sPriorityHandlingName"));
//		dto.setRemarks(rs.getString("sRemarks"));
//		dto.setCoverNoteNumber(rs.getString("sCovernoteSRCHSpy"));
//		dto.setCampaignCode(rs.getString("sCampCodeSRCHSpy"));
//		dto.setPolicyAddress(rs.getString("sCitySRCH_1"));
//		dto.setChequeNumber(rs.getString("sChqnoSRCH_1"));
//		dto.setVehicleNumber(rs.getString("sVehiclenoSRCH_1"));
//		dto.setTelephoneNumber(rs.getString("sTelnoSpy"));
//		dto.setAddress(rs.getString("sAddressDisp1"));
//		dto.setPermanentAddress(rs.getString("sPermAddressDisp1"));
//		dto.setPermanentMobile(rs.getString("sPermMobileDisp"));
//		dto.setDeliveryDate(rs.getString("sDeliveryDtDisp"));
//		dto.setMailingDate(rs.getString("sMailingDtDisp"));
//		   dto.setDespatchDate(rs.getString("DTCAPTUREDATE"));
//		dto.setDeliveryStatus(rs.getString("sDeliveryStatusDisp"));
//		dto.setConverNoteIssueDate(rs.getString("sCoveNoteIssueDateDisp"));
//		dto.setConsignmentNumber(rs.getString("sConsignNoDisp"));
//		dto.setModeOfDispatch(rs.getString("sDespModeDisp"));
//		dto.setDespatchThrough(rs.getString("sDespThruDisp"));
//		dto.setDeliveredTo(rs.getString("sDeliveredToDisp"));
//		dto.setSearchCriteria(rs.getString("sSearchCriteria"));
//		dto.setName(rs.getString("sNameSRCH"));
//		dto.setNameSearchBy(rs.getString("sNamesearchBy"));
//		dto.setChequeNumberPay(rs.getString("sChqnoSRCH"));
//		dto.setPolicies(rs.getString("sPolicy"));
//		dto.setPhoneNo(rs.getString("sContactNo"));
//		dto.setVip(rs.getString("sVIP"));
//		dto.setPolicyAsh(rs.getString("sPolicynoSRCH"));
//		dto.setProductName(rs.getString("sProductName"));
//		dto.setCampaignCode(rs.getString("sCampCodeSRCH"));
//		dto.setCombiPolicy(rs.getString("sCombiPolicynoSRCH"));
//		dto.setLifePolicy(rs.getString("sLifepolicynoSRCH"));
//		dto.setPolicyAddress(rs.getString("sCitySRCH"));
//		dto.setBankAccountNumber(rs.getString("sBankACSRCH"));
//		dto.setDebitCard(rs.getString("sDebitSRCH1"));
//		dto.setCreditCard(rs.getString("sCCnoSRCH1"));
//		dto.setEmail(rs.getString("sEmailSRCH"));
//		dto.setHealthCardNumber(rs.getString("sHCnoSRCH"));
//		dto.setTeleNumber(rs.getString("sTelno"));
//		dto.setEnterAgentCode(rs.getString("sAgCode1"));
//		dto.setTopRight(rs.getString("sAgentdocunid"));
//		dto.setAgCode(rs.getString("sAgCode"));
//		dto.setAgnetName(rs.getString("sAgName"));
//		dto.setDateOfBirth(rs.getString("sAgDOB"));
//		dto.setAgMobileNumber(rs.getString("sAgMobileno"));
//		dto.setAgCity(rs.getString("sAgLocation"));
//		dto.setAgState(rs.getString("sAgState"));
//		dto.setRegion(rs.getString("sAgRegion"));
//		dto.setEmaiId(rs.getString("sAgEmailid"));
//		dto.setLicencedNonLicenced(rs.getString("sAgLicence"));
//		dto.setPanNo(rs.getString("sAgPanno"));
//		dto.setLifePolicyAsh(rs.getString("sLifePolicynodisp"));
//		dto.setCombiPolicyAsh(rs.getString("sCombiPolicynodisp"));
//		dto.setPolicyPeriodFromTp(rs.getString("sPeriodFromdispTP"));
//		dto.setPolicyPeriodToTp(rs.getString("sPeriodTodispTP"));
//		dto.setVehicalAsh(rs.getString("sVehiclenodisp"));
//		dto.setVehicalMake(rs.getString("sVehiclemakedisp"));
//		dto.setModel(rs.getString("SMODELDISP"));
//		//dto.setPolicyPassword(rs.getString("sPolicyPassworddisp"));
//		dto.setRegisteredNumber(rs.getString("SREGPHDISP"));
//		dto.setMobileNumber(rs.getString("seditMobPh_2"));
//		dto.setState(rs.getString("SState"));
//		dto.setAlernateMobileNumber(rs.getString("SAltMob_3"));
//		dto.setEmail4(rs.getString("SEmail_4"));
//		dto.setResidencePhone(rs.getString("sResPh_5"));
//		dto.setOfficePhone(rs.getString("sOfficePh_6"));
//		dto.setOfficeFax(rs.getString("sOfficeFax_7"));
//		dto.setReceiptNumber(rs.getString("sReceiptNodisp"));
//		dto.setProcessingUnit(rs.getString("sPUdisp"));
//		dto.setAgentMobileNo(rs.getString("sAgentmobilNo"));
//		dto.setRenewalIdvNumber(rs.getString("sWWCIDVdisp"));
//		dto.setRenewalNcb(rs.getString("sWWCRnlNCBdisp"));
//		dto.setRenewalPremium(rs.getString("sWWCPremiumdisp"));
//		   dto.setStatus(rs.getString("SCURRENTSTATUS"));
//		dto.setOnlineRenewalOption(rs.getString("sWWCOnlineRenewalOptiondisp"));
//		dto.setSatisfactoryScore(rs.getString("sSatisfy_Score_TX"));
//		dto.setCustomerPolicyAsh(rs.getString("sCustPolicynodisp"));
//		dto.setHealthCardNo(rs.getString("sHCnodisp"));
//		dto.setClaimReportedNew(rs.getString("sClaimReportNewDisp"));
//		dto.setClaimPaid(rs.getString("sClaimPaidDisp"));
//		dto.setLinkNumber(rs.getString("sLinkDisp"));
//		dto.setResponseCommitedMonth(rs.getString("sResponseMon1"));
//		dto.setResponseCommitedYear(rs.getString("sResponseyear1"));
//		dto.setClaims(rs.getString("sClaimDisp"));
//		dto.setCovid19(rs.getString("scovidDisp"));
//		dto.setMailSentForComplaintClaim(rs.getString("sComplaintClaimMailSent"));
//		dto.setIntimationOfBccMembers(rs.getString("sBCCMembers"));
//		dto.setCity(rs.getString("sClaimscity"));
//		dto.setClaimLocation(rs.getString("sClaimLocation"));
//		dto.setClaimArea(rs.getString("sClaimArea"));
//		dto.setNewArea(rs.getString("sClaimAreaOther"));
//		dto.setInteractionType(rs.getString("sInteractionTypeDisp"));
//		dto.setClassification(rs.getString("sIClassificationDisp"));
//		dto.setHealthSubCategory(rs.getString("sHealthSubCat"));
//		dto.setUnderlyingCause(rs.getString("sCS_OPS"));
//		dto.setStateIc(rs.getString("sCtxtAState"));
//		dto.setCityIc(rs.getString("sCtxtAcity"));
//		dto.setIrdaStateId(rs.getString("sstateHIDE"));
//		dto.setReceivedRenewalNotice(rs.getString("sRenewalNotice"));
//		dto.setReceivedRenewalTeamCallback(rs.getString("sRenewalTeamCallback"));
//		dto.setInstaPayLink(rs.getString("sInstapaylink"));
//		dto.setCustomerEmail(rs.getString("sCustemail"));
//		dto.setMailRequestSent(rs.getString("sMailrequest"));
//		dto.setD2c(rs.getString("sD2C"));
//		dto.setSelectNeft(rs.getString("sNEFTClaim_1"));
//		dto.setNeftTransferForm(rs.getString("sNEFTClaimsForm_1"));
//		dto.setCustomerMailId1(rs.getString("sCustEmaildisp_1"));
//		dto.setSelectChangeRequestFormForInclusion(rs.getString("sClaim_2"));
//		dto.setChangeReqyestFormForInclusionForInsuredProcedure(rs.getString("sClaimsForm_2"));
//		dto.setCustomerEmailId2(rs.getString("sCustEmaildisp_2"));
//		dto.setSelectChangeRequestForm(rs.getString("sClaim_3"));
//		dto.setChangeRequestFormForSumIlnsuredProcedure(rs.getString("sClaimsForm_3"));
//		dto.setCustomerMailId3(rs.getString("sCustEmaildisp_3"));
//		dto.setSelectNameTransferMotorCarFormForInclusion(rs.getString("sClaim_4"));
//		dto.setNameTransferFormMotorCar(rs.getString("sClaimsForm_4"));
//		dto.setCustomerMailId4(rs.getString("sCustEmaildisp_4"));
//		dto.setSelectNameTransferTwoWheelerFormForInclusion(rs.getString("sClaim_5"));
//		dto.setNameTransferFormForTwoWheeler(rs.getString("sClaimsForm_5"));
//		dto.setCustomerMailId5(rs.getString("sCustEmaildisp_5"));
//		dto.setSelectProposerNameChangeRequestForm(rs.getString("sClaim_6"));
//		dto.setProposerNameChangeForm(rs.getString("sClaimsForm_6"));
//		dto.setCustomerMailId(rs.getString("sCustEmaildisp_6"));
//		dto.setRetentionTool(rs.getString("sRetention_Tool"));
//		dto.setBranch(rs.getString("sBranch"));
//		dto.setPremium(rs.getString("sPremiumAmountDisp"));
//		dto.setAcknowledgedmentSent(rs.getString("sAckStatusDisp"));
//		dto.setFinalResolutionSent(rs.getString("sFinalResStatusDisp"));
//		dto.setClaimForms(rs.getString("sClaimsForm"));
//		dto.setCustomerEmailDisp(rs.getString("sCustEmaildisp"));
//		dto.setIrdaOriginalTokenNumber(rs.getString("sOIRDATokenNo"));
//		dto.setComplaintInformed(rs.getString("sComplaintInformedDisp"));
//		dto.setAcceptedRejected(rs.getString("sAccepRej_1"));
//		dto.setDoYouWantToToReassign(rs.getString("sReassign"));
//		dto.setReassignto(rs.getString("sReassignTo"));
//		dto.setIntimatedBy(rs.getString("sIntimatedBy"));
//		dto.setIntimatedDateAndTime(rs.getString("sIntDateTime"));
//		dto.setDateOfLoss(rs.getString("sDateofloss"));
//		dto.setTimeOfLossHours(rs.getString("sClaimHours"));
//		dto.setTimeOfLossMin(rs.getString("sClaimMins"));
//		dto.setTimeOfLossAm(rs.getString("sClaimAM"));
//		dto.setRepairerName(rs.getString("sRepairerName"));
//		dto.setRepairerAddress(rs.getString("sRepairerAddss"));
//		dto.setRepairerContact(rs.getString("sRepairerContNo"));
//		dto.setRelationshipOfTheCaller(rs.getString("sRelationship"));
//		dto.setSpocPersonToBeContacted(rs.getString("sPersonSpoc"));
//		dto.setSpocPersonMobileNumber(rs.getString("sMobilenoClaim"));
//		dto.setDriverNameAtTheTimeOfAccident(rs.getString("sDriverName"));
//		dto.setIsInjured(rs.getString("sIsInjured"));
//		dto.setAccidentState(rs.getString("sAccState"));
//		dto.setAccidentCity(rs.getString("sAccCity"));
//		dto.setCurrentVehicalLocation(rs.getString("sCurrentVLocation"));
//		dto.setLossLocation(rs.getString("sLossLocation"));
//		dto.setNatureOfLoss(rs.getString("sNatureofloss"));
//		dto.setModeOfIntimation(rs.getString("sModofIntimation"));
//		dto.setDoYouWantToDpReassign(rs.getString("sDPReassign"));
//		dto.setDpReassignTo(rs.getString("sDPReassignTo"));
//		dto.setIrdaComments(rs.getString("sIRDAComment"));
//		dto.setApproverComments(rs.getString("sApprComment"));
//		dto.setCommentsComplaintMotorClaim(rs.getString("sCustomerUpdation"));
//		dto.setNatureOfRootCause(rs.getString("sNRCause"));
//		dto.setResolutionForRootCause(rs.getString("sCAComment"));
//		dto.setRootCauseFixed(rs.getString("sRCF"));
//		dto.setCommunicateWithTheCustomer(rs.getString("sCommunicate"));
//		dto.setSelectTheModeOfCommunication(rs.getString("sModeCom"));
//		dto.setMailWillBeSentTo(rs.getString("sCCMail"));
//		dto.setDoYouWantToCloseTheCall(rs.getString("sCloseCall"));
//		dto.setFeedback(rs.getString("schkfeedback"));
//		dto.setFollowUpCount(rs.getString("SFollowUpCount"));
//		dto.setFollowUpDays(rs.getString("snmFollowUpDays"));
//		dto.setFollowupDone(rs.getString("sFollowUpDone"));
//		dto.setFollowUpDate(rs.getString("sFollowUpDate"));
//		dto.setResolutionMode1(rs.getString("sResolutionMode1"));
//		dto.setResolutionMode2(rs.getString("sResolutionMode2"));
//		dto.setResolutionMode3(rs.getString("sResolutionMode3"));
//		dto.setResolutionMode4(rs.getString("sResolutionMode4"));
//		dto.setActivityNo(rs.getString("sActivityno"));
//		dto.setActivityName(rs.getString("sActivityname"));
//		dto.setFlag(rs.getString("sFlag"));
//		dto.setFunction(rs.getString("sFunction"));
//		dto.setThirdParty(rs.getString("sThirdParty"));
//		dto.setSlaDate(rs.getString("sDatetimeLog_1"));
//		dto.setTeamName(rs.getString("sTeamName"));
		   dto.setMembersResponsible(rs.getString("SMemberResp"));
//		dto.setSla(rs.getString("sSLA"));
//		dto.setEndDateTime(rs.getString("sSLA1DateTime"));
//		dto.setEscalationTo(rs.getString("sEscalation1"));
//		dto.setAshNumber(rs.getString("ctxtActivityno_1"));
//		dto.setActivityName1(rs.getString("ctxtActivityname_1"));
//		dto.setConditions(rs.getString("sCondition"));
//		dto.setSla1(rs.getString("sSLA_1"));
//		dto.setEndDateTime2(rs.getString("sSLA2DateTime"));
//		dto.setEscalationTo2(rs.getString("sEscalation2"));
//		dto.setSla2(rs.getString("sSLA_2"));
//		dto.setEndDateTime3(rs.getString("sSLA3DateTime"));
//		dto.setEscalationTo3(rs.getString("sEscalation3"));
//		dto.setIrdaComplaintTypeId(rs.getString("sIRDAID"));
//		dto.setIrdaComplaintDescriptionId(rs.getString("sIRDADescID"));
//		dto.setIrdaTat(rs.getString("sIRDATAT"));
//		dto.setActivitynoLog(rs.getString("sActivitynoLog"));
//		dto.setActivityNameLog(rs.getString("sActivitynameLog"));
//		dto.setIfReassignedToWhom(rs.getString("sReassignedLog"));
//		dto.setWaitingDays(rs.getString("sWaitingtimeLog"));
//		dto.setAwbNumber(rs.getString("sAWBNumber"));
		    dto.setSerialNumber(rs.getString("SERIALNO"));
//		dto.setDespatchDate(rs.getString("DTCAPTUREDATE"));
//		dto.setIsClosureRequsted(rs.getString("sIRDALetterDate"));
//        dto.setAddress1(rs.getString("sCtxtAdd1"));
//        dto.setAddress2(rs.getString("sCtxtAdd2"));
//        dto.setAddress(rs.getString("sCtxtAdd3"));
//        dto.setAddress(rs.getString("sCtxtAdd4"));
//        dto.setIsAddressCorrection(rs.getString("sAdressCorrection"));
//        dto.setIsAddressCorrectionDis(rs.getString("sAdressCorrectiondisp"));
//        dto.setPincode(rs.getString("sAPincode"));
//		dto.setCityCode(rs.getString("sACCityCodeDB"));
//		dto.setStateId(rs.getString("sACStateID"));
//		dto.setCityId(rs.getString("sACCityID"));
//		dto.setStateCode(rs.getString("sACStateCodeDB"));
//		dto.setIrdaCityId(rs.getString("SCityHIDE"));
//		dto.setSubUnderLyingCause1(rs.getString("scbUnderlyingCause_5"));
//		dto.setSubUnderLyingCause2(rs.getString("scbUnderlyingCause_6"));
//		dto.setSubUnderLyingCause1(rs.getString("scbUnderlyingCause_7"));
//		dto.setInteractionNum(rs.getString("ninteractioncount"));    
		}catch(Exception e){
			
			logger.info("Exception on CimsUpdatedMapper ",e);
		}
        return dto;
	}

}
